version: "3"

services:
  backend:
    build: backend
    links:
         - "cache:redis"

  nginx:
    image: nginx:latest
    container_name: kart_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "backend:api"
      - "frontend:fe"

  frontend:
    build: frontend

  cache:
    image: redis:latest
    container_name: kart_redis

